name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install PNPM
        uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: pnpm install
      - name: Run Tests
        run: pnpm test