name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: pnpm i --ignore-scripts
      - name: Unit Tests
        run: pnpm test